In [29]:
import pandas as pd
import numpy as np

In [30]:
#Importing Louisville Crime Data
louisville_crime_2020 = pd.read_csv('crime_2020_-2988378996369536818.csv')
louisville_crime_2020

C:\Users\Joe\AppData\Local\Temp\ipykernel_101012\3193522367.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  louisville_crime_2020 = pd.read_csv('crime_2020_-2988378996369536818.csv')

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,NIBRS_CODE,UCR_HIERARCHY,ATT_COMP,LMPD_DIVISION,LMPD_BEAT,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2019-12-31 03:30:00,FRAUD,FRAUD USE OF CREDIT CARD AFTER REPT LOST/STOLE...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2019-12-31 18:00:00,THEFT/LARCENY,"TBUT OR DISP ALL OTHERS > $500 BUT < $10,000",23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2019-12-31 23:30:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020-01-01 03:00:00,VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2019-12-31 12:00:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020-12-31 15:00:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH < $500,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206.0,70229
70229,80-20-077552,2020-12-31 15:38:00,2020-12-31 14:25:00,ASSAULT,ASSAULT - 4TH DEGREE (DOMESTIC VIOLENCE) MINOR...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210.0,70230
70230,80-20-077554,2020-12-31 16:25:00,2020-12-31 00:01:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH < $500,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228.0,70231
70231,80-20-077553,2020-12-31 15:39:00,2020-12-31 15:34:00,ASSAULT,HARASSMENT - PHYSICAL CONTACT - NO INJURY,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214.0,70232
70232,80-20-077555,2020-12-31 16:26:00,2020-12-30 20:30:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223.0,70233

In [31]:
# Creating a DataFrame from the CSV file
df = pd.read_csv('crime_2020_-2988378996369536818.csv')
df.head()

C:\Users\Joe\AppData\Local\Temp\ipykernel_101012\4175434342.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('crime_2020_-2988378996369536818.csv')

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,NIBRS_CODE,UCR_HIERARCHY,ATT_COMP,LMPD_DIVISION,LMPD_BEAT,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2019-12-31 03:30:00,FRAUD,FRAUD USE OF CREDIT CARD AFTER REPT LOST/STOLE...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2019-12-31 18:00:00,THEFT/LARCENY,"TBUT OR DISP ALL OTHERS > $500 BUT < $10,000",23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2019-12-31 23:30:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020-01-01 03:00:00,VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2019-12-31 12:00:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5

In [33]:
# Print column names
df.columns

Index(['INCIDENT_NUMBER', 'DATE_REPORTED', 'DATE_OCCURED', 'CRIME_TYPE',
       'UOR_DESC', 'NIBRS_CODE', 'UCR_HIERARCHY', 'ATT_COMP', 'LMPD_DIVISION',
       'LMPD_BEAT', 'PREMISE_TYPE', 'BLOCK_ADDRESS', 'City', 'ZIP_CODE',
       'ObjectId'],
      dtype='object')

In [34]:
# Renaming Columns for easier access

df.rename(columns={'INCIDENT_NUMBER': 'Incident_Number', 'DATE_REPORTED': 'Date_Reported', 'DATE_OCCURED': 'Date_Occurred', 'CRIME_TYPE': 'Crime_Type', 'UOR_DESC': 'UOR_Offense_Description', 'NIBRS_CODE': 'NIBRS_Code', 'UCR_HIERARCHY': 'UCR_Hierarchy', 'ATT_COMP': 'Att_Comp', 'LMPD_DIVISION': 'LMPD_Division', 'LMPD_BEAT': 'LMPD_Beat', 'PREMISE_TYPE': 'Premise_Type', 'BLOCK_ADDRESS': 'Block_Address', 'ZIP_CODE': 'ZIP_Code'}, inplace=True)
df.columns

Index(['Incident_Number', 'Date_Reported', 'Date_Occurred', 'Crime_Type',
       'UOR_Offense_Description', 'NIBRS_Code', 'UCR_Hierarchy', 'Att_Comp',
       'LMPD_Division', 'LMPD_Beat', 'Premise_Type', 'Block_Address', 'City',
       'ZIP_Code', 'ObjectId'],
      dtype='object')

In [35]:
# Finding and handling missing values
df.isnull().sum()

Incident_Number               0
Date_Reported                 0
Date_Occurred                 0
Crime_Type                    0
UOR_Offense_Description       0
NIBRS_Code                    0
UCR_Hierarchy              1770
Att_Comp                     61
LMPD_Division                 0
LMPD_Beat                     2
Premise_Type                  8
Block_Address                 0
City                         11
ZIP_Code                     46
ObjectId                      0
dtype: int64

In [36]:
df.isnull().sum() * 100 / len(df)

Incident_Number            0.000000
Date_Reported              0.000000
Date_Occurred              0.000000
Crime_Type                 0.000000
UOR_Offense_Description    0.000000
NIBRS_Code                 0.000000
UCR_Hierarchy              2.520183
Att_Comp                   0.086854
LMPD_Division              0.000000
LMPD_Beat                  0.002848
Premise_Type               0.011391
Block_Address              0.000000
City                       0.015662
ZIP_Code                   0.065496
ObjectId                   0.000000
dtype: float64

In [37]:
# Identifying data types of each column
df.dtypes

Incident_Number            object
Date_Reported              object
Date_Occurred              object
Crime_Type                 object
UOR_Offense_Description    object
NIBRS_Code                 object
UCR_Hierarchy              object
Att_Comp                   object
LMPD_Division              object
LMPD_Beat                  object
Premise_Type               object
Block_Address              object
City                       object
ZIP_Code                   object
ObjectId                    int64
dtype: object

In [40]:
# Converting 'Date_Reported' and 'Date_Occurred' to datetime format

df['Date_Reported'] = pd.to_datetime(
    df['Date_Reported'],
    errors='coerce'
)

df['Date_Occurred'] = pd.to_datetime(
    df['Date_Occurred'],
    errors='coerce'
)
df.dtypes

Incident_Number                    object
Date_Reported              datetime64[ns]
Date_Occurred              datetime64[ns]
Crime_Type                         object
UOR_Offense_Description            object
NIBRS_Code                         object
UCR_Hierarchy                      object
Att_Comp                           object
LMPD_Division                      object
LMPD_Beat                          object
Premise_Type                       object
Block_Address                      object
City                               object
ZIP_Code                           object
ObjectId                            int64
dtype: object

Parsing the date/time/day of week from the 2 date fields

In [42]:
df['reported_year'] = df['Date_Reported'].dt.year
df['reported_month'] = df['Date_Reported'].dt.month
df['reported_day'] = df['Date_Reported'].dt.day
df['reported_time'] = df['Date_Reported'].dt.time
df['reported_dow'] = df['Date_Reported'].dt.day_name()
df.head()

,Incident_Number,Date_Reported,Date_Occurred,Crime_Type,UOR_Offense_Description,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId,reported_year,reported_month,reported_day,reported_time,reported_dow
0,80-20-000117,2020-01-01 13:50:00,2019-12-31 03:30:00,FRAUD,FRAUD USE OF CREDIT CARD AFTER REPT LOST/STOLE...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1,2020,1,1,13:50:00,Wednesday
1,80-20-000292,2020-01-02 10:45:00,2019-12-31 18:00:00,THEFT/LARCENY,"TBUT OR DISP ALL OTHERS > $500 BUT < $10,000",23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2,2020,1,2,10:45:00,Thursday
2,80-19-096135,2020-01-01 00:26:00,2019-12-31 23:30:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3,2020,1,1,00:26:00,Wednesday
3,80-20-000234,2020-01-01 23:57:00,2020-01-01 03:00:00,VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4,2020,1,1,23:57:00,Wednesday
4,80-20-000294,2020-01-02 11:02:00,2019-12-31 12:00:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5,2020,1,2,11:02:00,Thursday

In [43]:
df['occurred_year'] = df['Date_Occurred'].dt.year
df['occurred_month'] = df['Date_Occurred'].dt.month
df['occurred_day'] = df['Date_Occurred'].dt.day
df['occurred_time'] = df['Date_Occurred'].dt.time
df['occurred_dow'] = df['Date_Occurred'].dt.day_name()
df.head()

,Incident_Number,Date_Reported,Date_Occurred,Crime_Type,UOR_Offense_Description,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,...,reported_year,reported_month,reported_day,reported_time,reported_dow,occurred_year,occurred_month,occurred_day,occurred_time,occurred_dow
0,80-20-000117,2020-01-01 13:50:00,2019-12-31 03:30:00,FRAUD,FRAUD USE OF CREDIT CARD AFTER REPT LOST/STOLE...,26B,PART II,COMPLETED,4TH DIVISION,435,...,2020,1,1,13:50:00,Wednesday,2019,12,31,03:30:00,Tuesday
1,80-20-000292,2020-01-02 10:45:00,2019-12-31 18:00:00,THEFT/LARCENY,"TBUT OR DISP ALL OTHERS > $500 BUT < $10,000",23H,PART I,COMPLETED,6TH DIVISION,613,...,2020,1,2,10:45:00,Thursday,2019,12,31,18:00:00,Tuesday
2,80-19-096135,2020-01-01 00:26:00,2019-12-31 23:30:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,1ST DIVISION,112,...,2020,1,1,00:26:00,Wednesday,2019,12,31,23:30:00,Tuesday
3,80-20-000234,2020-01-01 23:57:00,2020-01-01 03:00:00,VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE,290,PART II,COMPLETED,4TH DIVISION,424,...,2020,1,1,23:57:00,Wednesday,2020,1,1,03:00:00,Wednesday
4,80-20-000294,2020-01-02 11:02:00,2019-12-31 12:00:00,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,23F,PART I,COMPLETED,7TH DIVISION,736,...,2020,1,2,11:02:00,Thursday,2019,12,31,12:00:00,Tuesday

In [44]:
# Reordering columns to place new date-related columns next to the original date columns

cols_to_move = ['Date_Reported', 'reported_year', 'reported_month', 'reported_day', 'reported_time', 'reported_dow', 'Date_Occurred', 'occurred_year', 'occurred_month', 'occurred_day', 'occurred_time', 'occurred_dow']

cols = list(df.columns)

for col in cols_to_move:
    cols.remove(col)

insert_at = 3
for i, col in enumerate(cols_to_move):
    cols.insert(insert_at + i, col)

df = df[cols]
df.head()

,Incident_Number,Crime_Type,UOR_Offense_Description,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,FRAUD,FRAUD USE OF CREDIT CARD AFTER REPT LOST/STOLE...,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,THEFT/LARCENY,"TBUT OR DISP ALL OTHERS > $500 BUT < $10,000",2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,VEHICLE BREAK-IN/THEFT,TBUT OR DISP CONTENTS FROM VEH $500 OR > BUT <...,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5

In [46]:
cols_to_move = ['Crime_Type', 'UOR_Offense_Description']

cols = list(df.columns)

for col in cols_to_move:
    cols.remove(col)

insert_at = 13
for i, col in enumerate(cols_to_move):
    cols.insert(insert_at + i, col)

df = df[cols]
df.head()

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5

In [48]:
# Rediscovering data types after adding new columns
df.dtypes

Incident_Number                    object
Date_Reported              datetime64[ns]
reported_year                       int32
reported_month                      int32
reported_day                        int32
reported_time                      object
reported_dow                       object
Date_Occurred              datetime64[ns]
occurred_year                       int32
occurred_month                      int32
occurred_day                        int32
occurred_time                      object
occurred_dow                       object
Crime_Type                         object
UOR_Offense_Description            object
NIBRS_Code                         object
UCR_Hierarchy                      object
Att_Comp                           object
LMPD_Division                      object
LMPD_Beat                          object
Premise_Type                       object
Block_Address                      object
City                               object
ZIP_Code                           object
ObjectId                            int64
dtype: object

Data cleansing - replacing bad/Null/NaN values

In [50]:
# Cleaning 'ZIP_Code' column - removing floating point artifacts
df['ZIP_Code'] = (
    df['ZIP_Code']
    .astype(str)
    .str.replace(r'\.0$', '', regex=True)
)
df.head()

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5

In [52]:
# Cleaning 'ZIP_Code' column - correcting known erroneous entries
df['ZIP_Code'] = (
    df['ZIP_Code']
    .replace('40056', '40201')
    .replace('DRIVE', '40219')
    .replace('4291', '40291')
)

df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [58]:
# Continuing cleaning 'ZIP_Code' column - correcting known erroneous entries
df['ZIP_Code'] = (
    df['ZIP_Code']
    .replace(['', 'nan', 'NaN', 'None'], pd.NA)
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [60]:
df.loc[
    df['Block_Address'].str.upper().str.strip().eq('COMMUNITY AT LARGE')
    & df['ZIP_Code'].isna(),
    'ZIP_Code'
] = '40201'

df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [62]:
df['ZIP_Code'] = (
    df.groupby('LMPD_Beat')['ZIP_Code']
      .transform(lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x)
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [64]:
df.loc[
    df['Block_Address'].str.upper().str.strip().eq('INDIAN HILLS TRL / RIVER RD')
    & df['ZIP_Code'].isna(),
    'ZIP_Code'
] = '40207'

df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [65]:
df['City'] = (
    df['City']
    .replace('1719', 'HOLLYVILLA')
    .replace('LOUISV', 'LOUISVILLE')
    .replace('LOUUSVILLE', 'LOUISVILLE')
    .replace('', pd.NA)
    .fillna('LOUISVILLE')
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [66]:
df['Att_Comp'] = (
    df['Att_Comp']
    .replace('', pd.NA)
    .fillna('UNKNOWN')
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [67]:
df['Premise_Type'] = (
    df['Premise_Type']
    .replace('', pd.NA)
    .fillna('UNKNOWN')
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233

In [ ]:
df['UCR_Hierarchy'] = (
    df['UCR_Hierarchy']
    .replace(['', 'nan', 'NaN', None], pd.NA)
)
df

In [71]:
df['UCR_Hierarchy'] = (
    df['UCR_Hierarchy']
    .replace('', pd.NA)
    .fillna('UNKNOWN')
)
df

,Incident_Number,Date_Reported,reported_year,reported_month,reported_day,reported_time,reported_dow,Date_Occurred,occurred_year,occurred_month,...,NIBRS_Code,UCR_Hierarchy,Att_Comp,LMPD_Division,LMPD_Beat,Premise_Type,Block_Address,City,ZIP_Code,ObjectId
0,80-20-000117,2020-01-01 13:50:00,2020,1,1,13:50:00,Wednesday,2019-12-31 03:30:00,2019,12,...,26B,PART II,COMPLETED,4TH DIVISION,435,SERVICE / GAS STATION,4100 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215,1
1,80-20-000292,2020-01-02 10:45:00,2020,1,2,10:45:00,Thursday,2019-12-31 18:00:00,2019,12,...,23H,PART I,COMPLETED,6TH DIVISION,613,NON-ATTACHED RESD GARAGE/SHED/BULD,5200 BLOCK RUSSETT BLVD ...,LOUISVILLE,40218,2
2,80-19-096135,2020-01-01 00:26:00,2020,1,1,00:26:00,Wednesday,2019-12-31 23:30:00,2019,12,...,23F,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,S 16TH ST / W CHESTNUT ST ...,LOUISVILLE,40203,3
3,80-20-000234,2020-01-01 23:57:00,2020,1,1,23:57:00,Wednesday,2020-01-01 03:00:00,2020,1,...,290,PART II,COMPLETED,4TH DIVISION,424,HIGHWAY / ROAD / ALLEY,2700 BLOCK S 4TH ST ...,LOUISVILLE,40208,4
4,80-20-000294,2020-01-02 11:02:00,2020,1,2,11:02:00,Thursday,2019-12-31 12:00:00,2019,12,...,23F,PART I,COMPLETED,7TH DIVISION,736,DOCK/WHARF/FREIGHT/MODAL TERMINAL,1800 BLOCK SOUTH PARK RD ...,LOUISVILLE,40219,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70228,80-20-077551,2020-12-31 16:09:00,2020,12,31,16:09:00,Thursday,2020-12-31 15:00:00,2020,12,...,23F,PART I,COMPLETED,5TH DIVISION,525,PARKING LOT / GARAGE,700 BLOCK COCHRAN HILL RD ...,LOUISVILLE,40206,70229
70229,80-20-077552,2020-12-31 15:38:00,2020,12,31,15:38:00,Thursday,2020-12-31 14:25:00,2020,12,...,13B,PART II,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1600 BLOCK MOORE CT ...,LOUISVILLE,40210,70230
70230,80-20-077554,2020-12-31 16:25:00,2020,12,31,16:25:00,Thursday,2020-12-31 00:01:00,2020,12,...,23F,PART I,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,7600 BLOCK AVALON GARDEN DR ...,LOUISVILLE,40228,70231
70231,80-20-077553,2020-12-31 15:39:00,2020,12,31,15:39:00,Thursday,2020-12-31 15:34:00,2020,12,...,13B,PART II,COMPLETED,3RD DIVISION,331,RESIDENCE / HOME,3300 BLOCK RENWOOD BLVD ...,LOUISVILLE,40214,70232
70232,80-20-077555,2020-12-31 16:26:00,2020,12,31,16:26:00,Thursday,2020-12-30 20:30:00,2020,12,...,23F,PART I,COMPLETED,8TH DIVISION,824,RESIDENCE / HOME,12600 BLOCK OLD HENRY RD ...,LOUISVILLE,40223,70233